import { Crown, Trophy, Medal } from "lucide-react";

export const podiumConfig = [
  {
    position: "left" as const,
    rank: 2,
    index: 1,
    podiumHeight: "h-40",
    avatarSize: "h-20 w-20",
    hexSize: "h-24 w-24",
    neonColor: "#94a3b8",
    glowColor: "rgba(148,163,184,0.6)",
    bgGradient: "from-slate-400/20 to-slate-500/20",
    badgeBg: "bg-slate-500",
    icon: Medal,
    iconColor: "text-slate-400",
    nameSize: "text-base sm:text-lg",
    salesSize: "text-xl sm:text-2xl",
    salesColor: "text-slate-300",
    delay: 0.2,
    label: "VICE",
    labelSize: "text-4xl sm:text-5xl",
    borderColor: "border-slate-500/30",
    scanlineColor: "rgba(148,163,184,0.05)",
    ariaLabel: "Segundo lugar",
  },
  {
    position: "center" as const,
    rank: 1,
    index: 0,
    podiumHeight: "h-56",
    avatarSize: "h-32 w-32",
    hexSize: "h-36 w-36",
    neonColor: "#f59e0b",
    glowColor: "rgba(245,158,11,0.7)",
    bgGradient: "from-rank-gold/20 to-amber-500/20",
    badgeBg: "bg-rank-gold",
    icon: Crown,
    iconColor: "text-rank-gold",
    nameSize: "text-xl sm:text-2xl",
    salesSize: "text-3xl sm:text-4xl",
    salesColor: "text-rank-gold",
    delay: 0,
    label: "MVP",
    labelSize: "text-6xl sm:text-7xl",
    borderColor: "border-rank-gold/40",
    scanlineColor: "rgba(245,158,11,0.08)",
    ariaLabel: "Primeiro lugar",
  },
  {
    position: "right" as const,
    rank: 3,
    index: 2,
    podiumHeight: "h-32",
    avatarSize: "h-18 w-18",
    hexSize: "h-22 w-22",
    neonColor: "#b45309",
    glowColor: "rgba(180,83,9,0.5)",
    bgGradient: "from-amber-700/20 to-orange-900/20",
    badgeBg: "bg-amber-700",
    icon: Trophy,
    iconColor: "text-amber-600",
    nameSize: "text-sm sm:text-base",
    salesSize: "text-lg sm:text-xl",
    salesColor: "text-amber-500",
    delay: 0.4,
    label: "3º",
    labelSize: "text-3xl sm:text-4xl",
    borderColor: "border-amber-700/30",
    scanlineColor: "rgba(180,83,9,0.05)",
    ariaLabel: "Terceiro lugar",
  },
];
