import { useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { addDays, format } from "date-fns";

export function useEnrollInCadence() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (input: {
      sale_id: string;
      cadence_id: string;
      salesperson_id?: string;
    }) => {
      const { data: enrollment, error: enrollError } = await supabase
        .from("prospect_cadences")
        .insert({
          ...input,
          next_action_date: format(new Date(), "yyyy-MM-dd"),
        })
        .select()
        .single();

      if (enrollError) throw enrollError;
      
      // Tasks are now automatically generated by a database trigger 
      // (trg_generate_cadence_tasks) to ensure consistency across all enrollment methods.

      return enrollment;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["prospect-cadences"] });
      queryClient.invalidateQueries({ queryKey: ["todays-cadence-tasks"] });
      toast.success("Prospect inscrito na cadência!");
    },
    onError: (error: Error & { code?: string }) => {
      if (error.code === "23505") {
        toast.error("Prospect já está inscrito nesta cadência");
      } else {
        toast.error("Erro ao inscrever na cadência");
      }
      if (import.meta.env.DEV) {
        if (import.meta.env.DEV) console.error(error);
      }
    },
  });
}

export function usePauseCadence() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (saleId: string) => {
      const { data, error } = await supabase
        .from("prospect_cadences")
        .update({ status: "paused" })
        .eq("sale_id", saleId)
        .eq("status", "active")
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["prospect-cadences"] });
      queryClient.invalidateQueries({ queryKey: ["active-cadences-by-sales"] });
      queryClient.invalidateQueries({ queryKey: ["todays-cadence-tasks"] });
      toast.success("Cadência pausada!");
    },
    onError: (error) => {
      toast.error("Erro ao pausar cadência");
      if (import.meta.env.DEV) {
        if (import.meta.env.DEV) console.error(error);
      }
    },
  });
}

export function useResumeCadence() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (saleId: string) => {
      const { data, error } = await supabase
        .from("prospect_cadences")
        .update({ status: "active" })
        .eq("sale_id", saleId)
        .eq("status", "paused")
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["prospect-cadences"] });
      queryClient.invalidateQueries({ queryKey: ["active-cadences-by-sales"] });
      queryClient.invalidateQueries({ queryKey: ["todays-cadence-tasks"] });
      toast.success("Cadência retomada!");
    },
    onError: (error) => {
      toast.error("Erro ao retomar cadência");
      if (import.meta.env.DEV) {
        if (import.meta.env.DEV) console.error(error);
      }
    },
  });
}

export function useCancelCadence() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (saleId: string) => {
      const { data, error } = await supabase
        .from("prospect_cadences")
        .update({ 
          status: "cancelled",
          completed_at: new Date().toISOString(),
        })
        .eq("sale_id", saleId)
        .in("status", ["active", "paused"])
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["prospect-cadences"] });
      queryClient.invalidateQueries({ queryKey: ["active-cadences-by-sales"] });
      queryClient.invalidateQueries({ queryKey: ["todays-cadence-tasks"] });
      toast.success("Cadência cancelada!");
    },
    onError: (error) => {
      toast.error("Erro ao cancelar cadência");
      if (import.meta.env.DEV) {
        if (import.meta.env.DEV) console.error(error);
      }
    },
  });
}

export function useUpdateLeadStage() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ saleId, stage }: { saleId: string; stage: string }) => {
      const { data, error } = await supabase
        .from("prospect_cadences")
        .update({ funnel_stage: stage })
        .eq("sale_id", saleId);

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["prospect-cadences"] });
      queryClient.invalidateQueries({ queryKey: ["funnel-data"] });
      toast.success("Etapa do lead atualizada!");
    },
  });
}

