// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClientOptions } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Default timeout for all Supabase requests (ms) — prevents slow-query DoS
const DEFAULT_TIMEOUT_MS = Number(import.meta.env.VITE_SUPABASE_TIMEOUT_MS ?? 30000);

// Wrap global.fetch with an AbortController-based timeout.
// All Supabase requests (auth, database, realtime) go through this layer.
const globalFetch = globalThis.fetch.bind(globalThis);
globalThis.fetch = function fetchWithTimeout(
  input: RequestInfo | URL,
  init?: RequestInit & { signal?: AbortSignal | null }
): Promise<Response> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), DEFAULT_TIMEOUT_MS);
  const signal = init?.signal
    ? mergeSignals(init.signal, controller.signal)
    : controller.signal;

  return globalFetch(input, { ...init, signal }).finally(() => clearTimeout(timeout));
};

function mergeSignals(a: AbortSignal, b: AbortSignal): AbortSignal {
  const controller = new AbortController();
  a.addEventListener('abort', () => controller.abort(a.reason));
  b.addEventListener('abort', () => controller.abort(b.reason));
  return controller.signal;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: globalThis.fetch,
  },
} satisfies SupabaseClientOptions<Database>);